import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '../components/Navbar'
import Providers from './provider'
import Footer from '../components/Footer'





const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Gamma Net',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    
      <body className={`${inter} bg-red-50`}>
      
        <Providers>
        <Navbar/>
          {children}
          <Footer/>
        </Providers>
      
        </body>
    </html>
  )
}
