// components/ChannelList.js
import React from 'react';


const channels = [
  { id: 1, name: 'Aztv' },
  { id: 2, name: 'Mədəniyyət' },
  { id: 3, name: 'İdman Azərbaycan' },
  { id: 4, name: 'İctimai' },
  { id: 5, name: 'Space' },
  { id: 6, name: 'Xəzər' },
  { id: 7, name: 'Azad Azərbaycan' },
  { id: 8, name: 'Arb Tv' },
  { id: 9, name: 'Dünya Tv' },
  { id: 10, name: 'CBC Azərbaycan' },
  { id: 11, name: 'Star Tv' },
  { id: 12, name: 'ATV Türkiyə' },
  { id: 13, name: 'Shoü Tv' },
  { id: 14, name: 'TV 8' },
  { id: 15, name: 'Trt 1' },
  { id: 16, name: 'A Sport' },
  { id: 17, name: 'Авто 24' },
  { id: 18, name: 'Моя планета' },
  { id: 19, name: 'Real TV HD	' },
  { id: 20, name: 'Россия К	' },
  { id: 21, name: 'TRT Cocuk	' },
  { id: 22, name: 'Kral Pop	' },
  { id: 23, name: 'Power Türk HD	' },
  { id: 24, name: 'TMB Tv	' },
  { id: 25, name: 'Ani Tv	' },
  { id: 26, name: '5  Канал 	' },
  { id: 27, name: 'Киносвидание	' },
  { id: 28, name: 'Кинохит	' },
  { id: 29, name: 'Родное кино	' },
  { id: 30, name: 'Наше Новое Кино	' },
  { id: 31, name: 'Киномикс	' },
  { id: 32, name: 'Киносемья	' },
  { id: 33, name: 'СТС	' },
  { id: 34, name: 'Bloomberg Turk HT	' },
  { id: 35, name: 'Пятница	' },
  { id: 36, name: 'Кинопремьера HD	' },
  { id: 37, name: 'A Haber	' },
  { id: 38, name: 'MTV 90s	' },
  { id: 39, name: 'Мужское кино	' },
  { id: 40, name: 'Матч! Арена	' },
  { id: 41, name: 'ТНТ	' },
  { id: 42, name: 'Ю-ТВ	' },
  { id: 43, name: 'РТР Планета 	' },
  { id: 44, name: 'Индийское кино	' },
  { id: 45, name: 'DTX	' },
  { id: 46, name: 'Матч! ТВ	' },
  { id: 47, name: 'ТВ Центр	' },
  { id: 48, name: 'Киносерия	' },
  { id: 49, name: 'CNN International	' },
  { id: 50, name: 'BBC World News	' },
  { id: 51, name: 'EuroNews	' },
  { id: 52, name: 'Детский мир Телекл	' },
  { id: 53, name: 'Disney Channel	' },
  { id: 54, name: 'THT 4	' },
  { id: 55, name: '360 Tv Turk	' },
  { id: 56, name: 'Загородная жизнь	' },
  { id: 57, name: 'Русский Детектив	' },
  { id: 58, name: 'Nickelodeon	' },
  { id: 59, name: 'Карусель	' },
  { id: 60, name: 'Cartoon Network	' },
  { id: 61, name: 'Mezzo	' },
  { id: 62, name: 'Ru Tv	' },
  { id: 63, name: 'Музыка первого	' },
  { id: 64, name: 'Звезда	' },
  { id: 65, name: 'TLC	' },
  { id: 66, name: 'Discovery Channel	' },
  { id: 67, name: 'Ностальгия	' },
  { id: 68, name: 'НТВ	' },
  { id: 69, name: 'Кинокомедия 	' },
  { id: 70, name: 'Кухня Тв	' },
  { id: 71, name: 'Discovery Science	' },
  { id: 72, name: 'Real Tv	' },
  { id: 73, name: 'Power Türk Tv	' },
  { id: 74, name: 'Travel+Adventure	' },
  { id: 75, name: 'TRT Haber	' },
  { id: 76, name: 'Первый HD	' },
  { id: 77, name: 'CBS Reality	' },
  { id: 78, name: 'Авто плюс 	' },
  { id: 79, name: 'ID Xtra	' },
  { id: 80, name: 'Муз ТВ	' },
  { id: 81, name: 'Домашний	' },
  { id: 82, name: 'Охота и Рыбалка	' },
  { id: 83, name: 'Рен ТВ	' },
  { id: 84, name: 'ТВ-3	' },
  { id: 85, name: 'Че	' },
  { id: 86, name: 'TV1000	' },
  { id: 87, name: 'TV1000 Русское кино	' },
  { id: 88, name: 'Мама	' },
  { id: 89, name: 'Amedia 2	' },
  { id: 90, name: 'World Fashion	' },
  { id: 91, name: 'Телекафе	' },
  { id: 92, name: 'Первый канал	' },
  { id: 93, name: 'TV1000 Action	' },
  { id: 94, name: 'NTV Turk	' },
  { id: 95, name: 'Живая Планета 	' },
  { id: 96, name: 'Шансон ТВ	' },
  { id: 97, name: 'Россия 1	' },
  { id: 98, name: 'National Geographic	' },
  { id: 99, name: 'Viasat History	' },
  { id: 100, name: 'Россия К	' },
  { id: 101, name: 'Док	' },
  { id: 102, name: 'Матч! Боец	' },
  { id: 103, name: 'DMAX	' },
  { id: 104, name: 'Матч! Наш Спорт 	' },
  { id: 105, name: 'EuroSport 1	' },
  { id: 106, name: 'Матч! Игра	' },
  { id: 107, name: 'Матч! Футбол 1	' },
  { id: 108, name: 'Матч! Футбол 2	' },
  { id: 109, name: 'Cartoon Network Tur	' },
  { id: 110, name: 'MCM Top	' },
  { id: 111, name: 'THT Music	' },
  { id: 112, name: 'Матч! Футбол 3	' },
  { id: 113, name: 'Дом Кино	' },
  { id: 114, name: 'Россия 24	' },
  { id: 115, name: 'Kanal 7	' },
  { id: 116, name: 'Amedia 1	' },
  { id: 117, name: 'Bridge TV Hits	' },
  { id: 118, name: 'HISTORY	' },
  { id: 119, name: 'Мульт	' },
  { id: 120, name: 'ЕвроКино	' },
  { id: 121, name: 'Dream TURK	' },
  { id: 122, name: 'Европа Плюс ТВ	' },
  { id: 123, name: '2х2	' },
  { id: 124, name: 'Minika Cocuk	' },
  { id: 125, name: 'ARB Gunesh	' },
  { id: 126, name: 'ARB 24	' },
  { id: 127, name: 'MTV Azerbaycan	' },
  { id: 128, name: 'NR1 Turk HD	' },
  { id: 129, name: 'Minika Go	' },
  { id: 130, name: 'Gulli Girl	' },
  { id: 131, name: 'Jim jan	' },
  { id: 132, name: 'TIJI	' },
  { id: 133, name: 'Nickelodeon Junior	' },
  { id: 134, name: 'Amedia Premium	' },
  { id: 135, name: 'Amedia Hit	' },
  { id: 136, name: 'TV XXI	' },
  { id: 137, name: 'TRT BELGESEL	' },
  { id: 138, name: 'Da Vinci Learning	' },
  { id: 139, name: '365 дней	' },
  { id: 140, name: 'Akilli Tv	' },
  { id: 141, name: 'БОКС ТВ	' },
  { id: 142, name: 'CBC Sport HD	' },
  { id: 143, name: 'Матч! Футбол 1 HD	' },
  { id: 144, name: 'Матч! Футбол 2 HD	' },
  { id: 145, name: 'Матч! Футбол 3 HD	' },
  { id: 146, name: 'Дом Кино Премиум HD 	' },
  { id: 147, name: 'Кинопремьера HD	' },
  { id: 148, name: 'National Geographic HD	' },
  { id: 149, name: 'Nat Geo Wild HD	' },
  { id: 150, name: 'Kinomiks HD	' },
  { id: 151, name: 'HTB HD	' },
  { id: 152, name: 'AzTv HD	' },
  { id: 153, name: 'Show Tv HD	' },
  { id: 154, name: 'Kanal D HD	' },
  { id: 155, name: 'Мир Тв	' },
  { id: 156, name: 'РБК	' },
  { id: 157, name: 'Kanal D	' },
  { id: 158, name: '  *****	' },
  { id: 159, name: 'НСТ	' },
  { id: 160, name: 'Конный Мир HD	' },
  { id: 161, name: '*****HD	' },
  { id: 162, name: 'Русский роман	' },
  { id: 163, name: 'Русский Бестселлер	' },
  { id: 164, name: 'TRT BELGESEL HD	' },
  { id: 165, name: 'TV 2 DH	' },
  { id: 166, name: 'Animal Planet HD	' },
  { id: 167, name: 'Ictimai HD	' },
  { id: 168, name: 'Beyaz Tv HD' },

 
  




  // Diğer kanalları buraya ekleyebilirsiniz
];

const ChannelList = () => {
  return (
    <div className="container mx-auto mt-8 mb-8 ">
      <h1 className="text-2xl font-bold mb-4">TV Kanal Siyahısı</h1>
      <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
        {channels.map((channel) => (
          <div key={channel.id} className=" bg-gray-200 p-4 rounded-md text-center font-semibold">
            <div className='flex gap-3 items-center'>
                <p className='text-start'>{channel.id}.</p>
            <p className="text-center font-semibold">{channel.name}</p></div>
          
          </div>
        ))}
      </div>
    </div>
  );
};

export default ChannelList;
